### ISSUE TITLE
Downgrade to sqlite2, as sqlite3 does not work.

### ISSUE THREAD

**Issue by ksambhi** [sabd-project/sabd-desktop#6]
At the moment, sqlite3 causes a segment fault when using it, even if sqlite3 is compiled against electron headers:
![pasted image at 2016_08_17 04_10 pm](https://cloud.githubusercontent.com/assets/12299307/17742267/40974b1c-6497-11e6-941a-71236899ae5f.png)

**Update:** fixed as part of #5.  An es6 wrapper around splite3 was used ([`sqlite`](https://www.npmjs.com/package/sqlite)).

**Comment by jujhars13** [comment]
Understood, will have a look to see if we can downgrade to Sqlite 2 via
https://www.npmjs.com/package/sqlite
